#!/usr/bin/env node
/**
 * Write the README's "Verified, not assumed" block from a real benchmark run.
 *
 * The numbers on the front page must be reproducible, not remembered: `npm run
 * bench -- --json` already measures them (median over 40 samples at 100×20) and
 * prints a machine-readable report, so the README table is generated from that
 * report rather than typed by hand. A hand-typed table is a table that drifts,
 * and a drifting number on a front page is worse than no number.
 *
 * Usage:
 *
 *   node scripts/bench-report.mjs            # rewrite the block in both READMEs
 *   node scripts/bench-report.mjs --check    # fail if the committed block differs
 *
 * `--check` is what a release run uses: it re-measures and refuses to let the
 * README claim something the current tree does not do.
 *
 * What `--check` compares, and what it deliberately does not: **bytes, addressed
 * rows and clears must match exactly** (they are deterministic — the painter either
 * wrote three rows or it did not), while the **millisecond column is not compared**.
 * A median of 40 timing samples moves by a few tenths of a millisecond between runs
 * on the same machine, and a check that fails on that would be a flaky gate — the
 * thing this project spends the most effort avoiding. The number is on the page for a
 * reader, regenerated at release time; the row/byte/clear counts are the claim.
 */
import { spawnSync } from 'node:child_process'
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import process from 'node:process'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const START = '<!-- bench:begin -->'
/**
 * Action names for the Chinese block. The benchmark's own `what` strings are
 * English (they are the labels `npm run bench` prints), so the translated table
 * maps them by id instead of shipping English rows inside the Chinese README.
 */
const ZH_WHAT = {
  'stream-tick': '流式输出时的一次重绘',
  'waiting-tick': '等待卡片时钟走一格',
  'screen-scroll': '报告屏翻一页（PgDn / PgUp）',
  'picker-move': '菜单里移动一次光标',
  'setup-typing': '向导字段里打一个字符',
}
const END = '<!-- bench:end -->'

function measure() {
  const result = spawnSync(process.execPath, [join(ROOT, 'scripts', 'bench-b2.mjs'), '--json'], {
    cwd: ROOT,
    encoding: 'utf8',
    maxBuffer: 32 * 1024 * 1024,
  })
  if (result.status !== 0) {
    throw new Error(`bench failed (exit ${result.status}): ${result.stderr?.slice(-400) ?? ''}`)
  }
  const start = result.stdout.indexOf('{')
  if (start === -1) throw new Error('bench printed no JSON object')
  return JSON.parse(result.stdout.slice(start))
}

/** The action's name as the block prints it, per language. */
function scenarioLabel(scenario, language) {
  return language === 'zh' ? (ZH_WHAT[scenario.id] ?? scenario.what) : scenario.what
}

/** The block, in the language of the file it goes into. */
function blockFor(report, language) {
  const { columns, rows, runs, scenarios } = report
  const total = scenarios.reduce((sum, scenario) => sum + scenario.clears, 0)
  if (language === 'zh') {
    return [
      START,
      `在 ${columns}×${rows} 下实测，每个动作 40 次取中位（\`npm run bench\`；本节由 \`npm run bench:report\` 生成，`,
      '不是手抄的）：',
      '',
      '| 动作 | 毫秒 | 字节 | 寻址行 | 整屏清屏 |',
      '|---|---|---|---|---|',
      ...scenarios.map(scenario => `| ${scenarioLabel(scenario, 'zh')} | ${scenario.ms.toFixed(2)} | ${scenario.bytes} | ${scenario.rows} | **${scenario.clears}** |`),
      '',
      `五个动作合计 **${total} 次整屏清屏**。这条是这一版的性能承诺：不管终端多慢、链路多差，`,
      '画面按行增量重绘，不会因为一次 tick 把整屏重画一遍。',
      END,
    ].join('\n')
  }
  return [
    START,
    `Measured on ${columns}×${rows}, median of ${runs} runs per action (\`npm run bench\`; this block is`,
    'generated by `npm run bench:report`, not typed by hand):',
    '',
    '| Action | ms | bytes | rows addressed | full clears |',
    '|---|---|---|---|---|',
    ...scenarios.map(scenario => `| ${scenarioLabel(scenario, 'en')} | ${scenario.ms.toFixed(2)} | ${scenario.bytes} | ${scenario.rows} | **${scenario.clears}** |`),
    '',
    `**${total} full-screen clears** across all five actions. That is the performance promise for this`,
    'version: however slow the terminal and however bad the link, frames repaint by row — no tick',
    'repaints the whole screen.',
    END,
  ].join('\n')
}

/**
 * The committed block's per-scenario counts, read back out of the table: the label
 * is the first cell, and the last three cells are bytes / rows / clears.
 */
function committedCounts(text) {
  const from = text.indexOf(START)
  const to = text.indexOf(END)
  if (from === -1 || to === -1) return undefined
  const rows = []
  for (const line of text.slice(from, to).split('\n')) {
    const cells = line.split('|').map(cell => cell.trim()).filter(cell => cell !== '')
    // Header and separator rows are not data: the second cell of a data row is the
    // millisecond figure, so it has to parse as one.
    if (cells.length !== 5 || !Number.isFinite(Number(cells[1]))) continue
    const [, bytes, addressed, clears] = cells.slice(-4)
    rows.push({ label: cells[0], bytes: Number(bytes), rows: Number(addressed), clears: Number(clears.replaceAll('*', '')) })
  }
  return rows
}

const report = measure()
const check = process.argv.includes('--check')
let drifted = false

for (const [file, language] of [['README.en.md', 'en'], ['README.md', 'zh']]) {
  const path = join(ROOT, file)
  const text = readFileSync(path, 'utf8')
  const from = text.indexOf(START)
  const to = text.indexOf(END)
  if (from === -1 || to === -1) {
    console.log(`note: ${file} has no bench block yet (markers missing)`)
    continue
  }

  if (check) {
    const committed = committedCounts(text)
    const problems = []
    if (committed === undefined || committed.length !== report.scenarios.length) {
      problems.push(`the block lists ${committed?.length ?? 0} actions, the run measured ${report.scenarios.length}`)
    } else {
      for (const [index, scenario] of report.scenarios.entries()) {
        const row = committed.find(entry => entry.label === scenarioLabel(scenario, language))
        if (row === undefined) {
          problems.push(`no row for ${scenario.id}`)
          continue
        }
        if (row.bytes !== scenario.bytes) problems.push(`${scenario.id}: bytes ${row.bytes} ≠ ${scenario.bytes}`)
        if (row.rows !== scenario.rows) problems.push(`${scenario.id}: rows ${row.rows} ≠ ${scenario.rows}`)
        if (row.clears !== scenario.clears) problems.push(`${scenario.id}: clears ${row.clears} ≠ ${scenario.clears}`)
      }
    }
    if (problems.length > 0) {
      drifted = true
      console.error(`${file}: FAIL`)
      for (const problem of problems) console.error(`  - ${problem}`)
    } else {
      console.log(`${file}: counts match (ms column not compared — see the header note)`)
    }
    continue
  }

  const next = `${text.slice(0, from)}${blockFor(report, language)}${text.slice(to + END.length)}`
  if (next === text) {
    console.log(`${file}: up to date`)
    continue
  }
  writeFileSync(path, next)
  console.log(`${file}: block rewritten from the measured run`)
}

if (check) {
  if (drifted) {
    console.error('FAIL: the README verification block is stale; run `npm run bench:report`')
    process.exit(1)
  }
  console.log('OK: every README count matches a fresh measured run')
  process.exit(0)
}
console.log(`measured clears: ${report.scenarios.reduce((sum, s) => sum + s.clears, 0)}`)
